(defun link-mobility ()
  (let ((a (channel "a"))
	(c (channel "b")))
    (labels ((p (x) 
	       (format t "P: ~a~%" x)
	       (-> c x))
	     (q (y) 
	       (let ((x (<- c)))
		 (format t "Q: ~a~%" x)
		 (-> x y)))
	     (r ()  (format t "R: ~a~%" (<- a))))
      (par (list			
	    (curry #'p a)
	    (curry #'q 5)
	    #'r)))))
